set(INSTALL_PATH "${CMAKE_SOURCE_DIR}/../1.Install_location")

install(TARGETS BasicGUI
    RUNTIME DESTINATION "${INSTALL_PATH}"
    BUNDLE DESTINATION "${INSTALL_PATH}"
    LIBRARY DESTINATION "${INSTALL_PATH}"
)